spring:
  application:
    name: springboot-prometheus
  mvc:
    validation:
      enabled: true
  shardingsphere:
    datasource:
      names:  master,slave0
      master:
        url: jdbc:mysql://localhost:3306/test
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        username: hongyuqin
        password: 123456
      slave0:
        url: jdbc:mysql://localhost:3307/test
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        username: hongyuqin
        password: 123456
    mode:
      type: Memory # 内存模式
    props:
      sql-show: true
    rules:
      readwrite-splitting:
        load-balancers:
          alg_round:
            type: ROUND_ROBIN
        data-sources:
          myds:
            type: Static
            load-balancer-name: alg_round
            props:
              write-data-source-name: master
              read-data-source-names: slave0

  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8858
        heartbeat-interval-ms: 500
logging:
  level:
    org:
      apache:
        kafka: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true