spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: G1Test
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      bootstrap-servers: 127.0.0.1:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      auto-offset-reset: earliest

logging:
  level:
    org:
      apache:
        kafka: INFO