server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
spring:
  application:
    name: g1test
  # Nacos配置
  cloud:
    nacos:
      # 配置中心
      config:
        server-addr: localhost:8848
        file-extension: yaml
        refresh-enabled: true
        import-check:
          enabled: false
        # 共享配置
        shared-configs:
          - data-id: g1test.yaml
            group: DEFAULT_GROUP
            refresh: true
        # 扩展配置
        extension-configs:
          - data-id: g1test.yaml
            group: DEFAULT_GROUP
            refresh: true
      # 服务发现
      discovery:
        server-addr: localhost:8848
  config:
    import: optional:nacos:g1test.yaml