spring:
  application:
    name: G1Test
  mvc:
    validation:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx1.
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      auto-offset-reset: earliest
      #isolation-level: read_committed

logging:
  level:
    org:
      apache:
        kafka: INFO