spring:
  config:
    import: optional:nacos:g1test.yaml?group=DEFAULT_GROUP
  application:
    name: g1test
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

      discovery:
        server-addr: 127.0.0.1:8848